# Example Choreo Component Config

components: Seo Info
  - name: 
    port: 3000
    type: REST
    networkVisibility: Public
    settings:
      runtime: nodejs12.x
      environment:
        NODE_ENV: production
      # Add more settings as needed

